"""Builds tints.css from the game's graffiti tints: a disc in each tint's color, as the tile image "tint_<id>", and
a "tint-<id>" class washing any tile image in it (ICS2Menus::SetItemImageTint).

    pip install vpk
    py gen_tints.py "<CS2>/game/csgo/pak01_dir.vpk"

Rerun after an update adds tints."""

import os
import re
import sys

import vpk

OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "panorama",
    "styles",
    "custom_game",
    "cs2menus",
    "tints.css",
)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text = (
        vpk.open(sys.argv[1])
        .get_file("scripts/items/items_game.txt")
        .read()
        .decode("utf-8", "replace")
    )
    start = text.index('"graffiti_tints"')
    block = text[start : text.index("\n\t}", start)]
    tints = re.findall(
        r'"(\w+)"\s*\{\s*"id"\s+"(\d+)"\s+"hex_color"\s+"(#[0-9a-fA-F]{6})"', block
    )
    assert tints, "no graffiti tints found"
    out = "/* Generated by workshop/tools/gen_tints.py from the game's graffiti_tints, don't edit by hand. */\n"
    for name, tint, color in sorted(tints, key=lambda t: int(t[1])):
        out += (
            f"/* {name} */\n"
            f".img-tint_{tint} {{\n"
            '\tbackground-image: url("s2r://panorama/images/custom_game/cs2menus/badge_disc.vsvg");\n'
            f"\twash-color: {color.lower()};\n"
            "}\n\n"
            f".tint-{tint} {{\n"
            f"\twash-color: {color.lower()};\n"
            "}\n\n"
        )
    open(OUT, "w", encoding="utf-8", newline="\n").write(out.rstrip("\n") + "\n")
    print(f"tints.css: {len(tints)} tints")


if __name__ == "__main__":
    main()
